opportunity/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from opportunity.tracker.views import PositionCommentCreate, PositionCommentDetail

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'opportunity.views.home', name='home'),
    # url(r'^opportunity/', include('opportunity.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^prospect/(?P<op>existing)', 'opportunity.tracker.views.companyDispatch'),
    (r'^prospect/(?P<op>add)', 'opportunity.tracker.views.companyEdit'),
    (r'^prospect/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.companyEdit'),
    (r'^prospect/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.companyDelete'),

    (r'^contact/(?P<op>existing)', 'opportunity.tracker.views.personDispatch'),
    (r'^contact/(?P<op>add)$', 'opportunity.tracker.views.personEdit'),
    (r'^contact/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.personEdit'),
    (r'^contact/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.personDelete'),
    
    (r'^position/(?P<op>add)$', 'opportunity.tracker.views.positionEdit'),
    (r'^position/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.positionEdit'),
    (r'^position/(?P<op>detail)/(?P<id>\d+)$', PositionCommentDetail.as_view()),
    (r'^position/(?P<op>detail)/(?P<id>\d+)/(?P<mentee_id>\d+)$', PositionCommentDetail.as_view()),
    (r'^position/(?P<op>active)/(?P<id>\d+)$', 'opportunity.tracker.views.positionActivation'),
    (r'^position/(?P<op>inactive)/(?P<id>\d+)$', 'opportunity.tracker.views.positionActivation'),
    (r'^position/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.positionDelete'),
    
    (r'^newactivity/', 'opportunity.tracker.views.newactivity'), # dispatch activity
    
    (r'^interview/(?P<op>add)$', 'opportunity.tracker.views.interviewEdit'), # add 
    (r'^interview/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.interviewEdit'), # edit
    (r'^interview/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.interviewDelete'), # delete 
    
    (r'^apply/(?P<op>add)$', 'opportunity.tracker.views.applyForEdit'), # add
    (r'^apply/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.applyForEdit'), # edit
    (r'^apply/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.applyForDelete'), # delete
    
    (r'^networking/(?P<op>add)$', 'opportunity.tracker.views.networkingEdit'), # add
    (r'^networking/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.networkingEdit'), # edit
    (r'^networking/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.networkingDelete'), # delete
        
    (r'^conversation/(?P<op>add)$', 'opportunity.tracker.views.conversationEdit'), # add
    (r'^conversation/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.conversationEdit'), # edit
    (r'^conversation/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.conversationDelete'), # del

    (r'^mentormeeting/(?P<op>add)$', 'opportunity.tracker.views.mentormeetingEdit'), # add
    (r'^mentormeeting/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.mentormeetingEdit'), # edit
    (r'^mentormeeting/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.mentormeetingDelete'), # del

    (r'^mentorship/(?P<op>add)$', 'opportunity.tracker.views.mentorshipEdit'), # add
    (r'^mentorship/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.mentorshipEdit'), # edit
    (r'^mentorship/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.mentorshipDelete'), # del

    (r'^lunch/(?P<op>add)$', 'opportunity.tracker.views.lunchEdit'),
    (r'^lunch/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.lunchEdit'),
    (r'^lunch/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.lunchDelete'),
    
    (r'^dashboard/$', 'opportunity.tracker.views.dashboard'),
    (r'^dashboard/(?P<mentee_id>\d+)$', 'opportunity.tracker.views.dashboard'),
    (r'^profile/$','opportunity.tracker.views.profileView'),
    (r'^profile/(?P<mentee_id>\d+)$','opportunity.tracker.views.profileView'),

    (r'^$','opportunity.tracker.views.toplevelView'),
    (r'^coordinator/$','opportunity.tracker.views.coordinatorView'),
    (r'^books/$','opportunity.tracker.views.books'),
    (r'^venues/$','opportunity.tracker.views.venues'),
    (r'^about/$','opportunity.tracker.views.about'),
    
    (r'^pitch/(?P<op>add)$', 'opportunity.tracker.views.pitchEdit'), 
    (r'^pitch/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.pitchEdit'),  
    (r'^pitch/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.pitchDelete'),  
    
    (r'^onlinePresence/(?P<op>add)$', 'opportunity.tracker.views.onlinePresenceEdit'),
    (r'^onlinePresence/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.onlinePresenceEdit'),
    (r'^onlinePresence/(?P<op>del)/(?P<id>\d+)$', 'opportunity.tracker.views.onlinePresenceDelete'),
    
    (r'^par/(?P<op>add)$', 'opportunity.tracker.views.parEdit'),
    (r'^par/(?P<op>edit)/(?P<id>\d+)$', 'opportunity.tracker.views.parEdit'),
    (r'^par/(?P<op>del)/(?P<id>\d+)/(?P<divId>\w+)$', 'opportunity.tracker.views.parDelete'),
    
    (r'^comment/add$', 'opportunity.tracker.views.dispatchCommentCreate'),
    (r'^comment/position/add$', PositionCommentCreate.as_view() ),

    (r'^login/$', 'opportunity.tracker.views.loginRequest'),
    (r'^logout/$', 'opportunity.tracker.views.logoutRequest'),
    (r'^register/$','opportunity.tracker.views.registration'),
    (r'^resetpassword/passwordsent$','django.contrib.auth.views.password_reset_done'),
    (r'^resetpassword/$','django.contrib.auth.views.password_reset'),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$','django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)

urlpatterns += staticfiles_urlpatterns()

opportunity/tracker/models.py
from __future__ import unicode_literals
import calendar
import datetime
import logging

from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.utils import six

logger = logging.getLogger(__name__)


def secret_society(user_profile, veiwing_profile_id):
    '''
    Given the UserProfile for the current user, compute a list of
    UserProfiles which are either mentors to and job seekers supported
    by this user.

    viewing_profile_id used to determine which page is being viewed and set
    the selectors default.
    '''
    ret = [('self', user_profile.id,
            True if user_profile.id == veiwing_profile_id else False)]
    # Retrieves all mentorships in which the current user is either
    # a jobseeker or mentor?
    m_list = Mentorship.objects.filter(
        Q(jobseeker=user_profile) | Q(mentor=user_profile))

    for m in m_list:
        if m.jobseeker != user_profile:
            ret.append((m.jobseeker.user.first_name.strip()
                        + ' ' + m.jobseeker.user.last_name.strip(),
                        m.jobseeker.id,
                        True if m.jobseeker.id == veiwing_profile_id else False))
        else:
            ret.append((m.mentor.user.first_name.strip()
                        + ' ' + m.mentor.user.last_name.strip(),
                        m.mentor.id,
                        True if m.mentor.id == veiwing_profile_id else False))
    return ret


def perm_and_params(requester, target_id):
    '''
    Given a UserProfile and a target uid, return a dict which contains
    permission and parameters with respect to whether the requestion
    can view the page.

    'perm_p' - boolean - can requester view this page?
    'page_owner_p' - boolean - Who owns the page ?
    'page_owner_name' - What is the name of the page owner?
    'profile_id' - What is the uid of the content to display?
    'warning_message' - Warning message to display if any ?
    '''
    page_options = {}
    page_options['perm_p'] = False
    page_options['page_owner_p'] = False
    page_options['page_owner_name'] = 'Unauthorized'
    page_options['profile_id'] = -1
    page_options['warning_message'] = None

    if target_id:
        # request to view someone elses page
        # perm_p is false by default. So, no need for else block

        if target_id and may_access_control(requester.id,
                                            target_id):
            if target_id == requester.id:
                page_options['profile_id'] = requester.id
                page_options['page_owner_p'] = True
                page_options['page_owner_name'] = 'My'
                page_options['perm_p'] = True
            else:
                page_options['profile_id'] = target_id
                mentee = UserProfile.objects.get(pk=target_id)
                page_options['page_owner_name'] = mentee.user.username.strip() + "'s"
                page_options['perm_p'] = True
    else:
        # no target id - what's the right default?
        # perm_p is false by default. Coordinator should always
        # be associated mentee id. if not, the default generates an error.
        if requester.is_job_seeker():
                page_options['profile_id'] = requester.id
                page_options['page_owner_p'] = True
                page_options['page_owner_name'] = 'My'
                page_options['perm_p'] = True
        elif requester.is_mentor():
            mentee_id, err_message = requester.has_mentee()
            if mentee_id and may_access_control(requester.id, mentee_id):
                page_options['profile_id'] = mentee_id
                mentee = UserProfile.objects.get(pk=mentee_id)
                page_options['page_owner_name'] = mentee.user.username.strip() + "'s"
                page_options['perm_p'] = True
            else:
                # mentor is logged in but has no mentee.
                page_options['profile_id'] = requester.id
                page_options['page_owner_p'] = True
                page_options['page_owner_name'] = 'My'
                page_options['perm_p'] = True
                warning_message = 'No mentee assigned, yet.'
    return page_options


def may_access_control(requester_id, target_id):
    '''
    can user with requester_id access a page for target_id?

    requester_id - is user profile id who wants access
    target_id - is user profile id owns the data.

    '''
    ret = False
    # urls pass ints as strings. What if someone forgets to convert them?
    if not (isinstance(requester_id, int) and isinstance(target_id, int)):
        logger.error('mentor ids must be ints')
        return False
    # find UserProfile for requestor
    user_req = UserProfile.objects.get(pk=requester_id)
    if user_req.is_upglo_staff:
        # UpGlo staff can access any page.
        ret = True
    elif requester_id == target_id:
        # Requester owns requested page
        ret = True
    else:
        # is there a mentorship relationship between aRequester and aTarget?
        m_rel = Mentorship.objects.filter(
            (Q(jobseeker=requester_id) & Q(mentor=target_id)) |
            (Q(jobseeker=target_id) & Q(mentor=requester_id)))
        if len(m_rel) == 1:
            ret = True
    return ret


@python_2_unicode_compatible
class UserProfile(models.Model):
    """
    A UserProfile is a person which uses our system.
    """
    user = models.OneToOneField(User)
    title = models.CharField(max_length=32)
    is_upglo_staff = models.BooleanField(default=False)
    JOB_SEEKER = "jobseeker"
    MENTOR = "mentor"
    COORDINATOR = "coordinator"
    ROLES_AT_UPGLO = (
        (JOB_SEEKER, "Job seeker"),
        (MENTOR, "Mentor"),
        (COORDINATOR, "Coordinator"),
    )
    role = models.CharField(max_length=12,
                            choices=ROLES_AT_UPGLO,
                            default=JOB_SEEKER)

    def __str__(self):
        return self.user.username

    def is_coordinator(self):
        '''
        Is a coordinator?
        '''
        return self.role == self.COORDINATOR

    def is_job_seeker(self):
        '''
        is a job seeker?
        '''
        return self.role == self.JOB_SEEKER

    def is_mentor(self):
        '''
        Is a mentor?
        '''
        return self.role == self.MENTOR

    def is_mentor_of(self, js_id):
        '''
        Is this user the mentor of id?
        '''
        if js_id:
            rc = True if may_access_control(self.id, js_id) else False
        else:
            rc = False
        return rc

    def has_mentee(self):
        '''
        Has this user been assigned to work with a job seeker?
        Given a user id return job seek id of mentee if any, else None
        '''
        rc = None
        err_msg = None
        if self.is_mentor():
            m_rel = Mentorship.objects.filter(mentor__id=self.id)
            if len(m_rel) >= 1:
                rc = m_rel[0].jobseeker_id
            else:
                err_msg = 'No mentee has been assigned, yet.'
        else:
            err_msg = 'You must be a mentor to view this page'
        return rc, err_msg

    def get_mentorship(self):
        '''
        Given user id return mentorship or None if there isn't one.
        '''
        rc = None
        if self.is_job_seeker():
            rc = Mentorship.objects.filter(jobseeker__id=self.id)
            if len(rc) >= 1:
                rc = rc[0]
        return rc


# UserProfile is associated with the User table. Listen for the post_save
# signal. Create a profile when new User added.


def create_user_profile(sender, instance, created, **kwargs):
    """
    This is the callback associated with the post_save signal on User.
    """
    if created:
        UserProfile.objects.create(user=instance)

# register for post_save signal on User
post_save.connect(create_user_profile, sender=User)


@python_2_unicode_compatible
class Mentorship(models.Model):
    '''
    A mentor assists a mentee with respect to finding a job.
    UpGlo Mentorships last five months.
    '''
    jobseeker = models.ForeignKey(UserProfile, related_name='jobseeker')
    mentor = models.ForeignKey(UserProfile, related_name='mentor')
    startDate = models.DateField()  # should be set in UI
    expirationDate = models.DateField(blank=True, null=True)  # computed

    def __str__(self):
        return '%s / %s' % (self.jobseeker, self.mentor)

    def is_active(self):
        return not self.has_expired()

    def has_expired(self):
        return datetime.date.today() > self.expirationDate

    def set_expiration(self):
        duration = 5  # in months
        y = self.startDate.year
        m = self.startDate.month + duration
        d = self.startDate.day
        if (m > 12):
            m = m % 12
            y += 1
        expiration = datetime.date(y, m, 1)
        # check if the start month has more days then the expiration month
        (dontcare, daysInThisMonth) = calendar.monthrange(y, m)
        if d >= daysInThisMonth:
            d = daysInThisMonth
        self.expirationDate = expiration + datetime.timedelta(d - 1)

    class Meta:
        ordering = ['-startDate']


@python_2_unicode_compatible
class Company(models.Model):
    name = models.CharField(_('Name'), max_length=32)
    division = models.CharField(_('Division'),
                                max_length=64,
                                blank=True, null=True)
    address = models.CharField(_('Address'), max_length=128)
    city = models.CharField(_('City'), max_length=32)
    state_province = models.CharField(_('State or Province'), max_length=32)
    country = models.CharField(
        _('Country'),
        max_length=3)   # select from three digit country code.
    zipCode = models.CharField(

opportunity/templates/about.html
{% extends "base.html" %}
{% block content %}
<article>
<h1>Seeking a job</h1>
<div class="row">
	<div class="col-md-6">
	<p>Most of us at one time or another need to go out and find a job. Sometimes it is easy, but often it is a challenge.  In these difficult economic times, it is harder. This site is dedicated to helping job seekers.</p>
	<p> There are many good resources online. The combination of <a href="http://www.linkedin.com/">LinkedIn</a> and <a href="http://www.meetup.com/">Meetup</a> are great for business networking. There are job boards and aggregation sites which allow you find job openings at many companies.</p>
	</div>

	<div class="col-md-6">
	<p>It is common for companies to use computer systems to track their interactions with job seekers and filter resumes. What if there was a system for job seeker?</p>
	<p class="well">A dashboard from which one could track interactions (e.g., applied for a position, spoke with someone, interviewer with some group) with companies. Investigating what is important to them to allow you to put together a value proposition and hone your elevator pitch.</p>
	</div>
</div>
</br>
<div class="row">
	<blockquote><p>Social networks are a household word today. One of the seminal works that lead to these social networks is <a href="http://sociology.stanford.edu/people/mgranovetter/documents/granstrengthweakties.pdf">The Strength of Weak Ties</a> <footer>by Mark S. Granovetter</footer>
	</blockquote>
</div>
<p>He was a PhD student at John Hopkins University studying how poeple found jobs. <b>Don't go job hunting alone!</b> Today's social networks are big on sharing. The word <b>share</b> appears in Granovetter's paper twice. Leveraging your social network is essential on the job hunt but there is a time when you want to confide in your family, close friends or a mentor. This website can help with that. By default, you nothing is shared. When you want to get some feedback from close associates, you can share your portfolio with them. </p>
<div style="text-align:center" >
  <embed 
     width="420" height="345"
     src="http://www.youtube.com/v/zkTf0LmDqKI"
     type="application/x-shockwave-flash">
  </embed>
</div>
</article>

{% endblock %}

opportunity/templates/books.html
{% extends "base.html" %}
{% block content %}

			<h1>Books</h1>
<p>
	<table border="1">
		<tr>
			<th>Book</th>
			<th>Description</th>
		</tr>
		<tr>
			<td> <iframe src="http://rcm.amazon.com/e/cm?t=johker-20&o=1&p=8&l=as1&asins=1607741474&IS1=1&ref=tf_til&fc1=000000&lt1=_blank&m=amazon&lc1=0000FF&bc1=FFFFFF&bg1=FFFFFF&npa=1&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe></td>
			<td><b>What Color Is Your Parachute?</b> is a classic job search book. It helps you find the kind of work about which you are passionate, take stock of your skills and actively pursue it.</td>
		</tr>
		<tr>
			<td>
			<iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=FFFFFF&IS1=1&npa=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=johker-20&o=1&p=8&l=as1&m=amazon&f=ifr&ref=tf_til&asins=0307888908" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe></td>
			<td><b>The Start-up of You</b> is a new book by Reid Hoffman, the CEO of LinkedIn, and Ben Casnocha. They apply key concepts from the startup world to the process of hunting for a job. These authors believe there are there things you need: assets(skills), aspiration(passion) and market reality(someone willing to pay for it).   </td>
		</tr>
		<tr>
			<td><iframe src="http://rcm.amazon.com/e/cm?t=johker-20&o=1&p=8&l=as1&asins=098478280X&IS1=1&ref=tf_til&fc1=000000&lt1=_blank&m=amazon&lc1=0000FF&bc1=FFFFFF&bg1=FFFFFF&npa=1&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
</td>
			<td><b>Cracking the Coding Interview</b> explains and helps you practice for job interviews in the software industry.</td>
		</tr>
		<tr>
			<td><iframe src="http://rcm.amazon.com/e/cm?t=johker-20&o=1&p=8&l=as1&asins=047012167X&IS1=1&ref=tf_til&fc1=000000&lt1=_blank&m=amazon&lc1=0000FF&bc1=FFFFFF&bg1=FFFFFF&npa=1&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
 </td>
			<td><b>Programming Interviews Exposed</b> explains and helps you practice for job interviews in the software industry.</td> 
		</tr>
	</table>
</p>

{% endblock %}

opportunity/templates/company_form.html
{% extends "base.html" %}
{% block content %}

<!--

The company model is distinct from other models in tracker because we
can glean information for other sources on the web (i.e., crunchbase
). This is simply more detail to present.

[aside: track_form.html is a generic templete. if you are starting a
new model/form, that is the place to start. 

-->

    <h1>{{ title }}</h1>
    
    {{ desc }} 
    <br/>
{% if activity and company_list %}
    <div id="select-existing">
      <fieldset>
	<legend>existing:</legend>
	<form action="/prospect/existing">
	  <select name="co_id">
	    {% for co in company_list %}
	     <option value="{{ co.id }}">{{ co.name }}</option>
	    {% endfor %}
	  </select>
          {% if activity %}
	  <input type="hidden" name="activity" value="{{ activity }}" >
          {% endif %}
	  <input type="submit" value="Submit">
	</form>
      </fieldset>
    </div>
    <br/>
    <div style="text-align: center;font-size: large"> Or </div>
{% endif %}
    <fieldset>
      <legend>{{ legend }}</legend>

      {% if form.errors %}
      <p style="color: red;">
        Please correct the error{{ form.errors|pluralize }} below.
      </p>
      {% endif %}

      <form action="" method="post">
        <table>
	  {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
      </form>
    </fieldset>
            
{% endblock %}

opportunity/templates/coordinator.html
{% extends "base.html" %}

{% block page_specific_js %} 
<link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
 <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<script>
    $(document).ready( function () {
        $('#table_id').dataTable();
    } );
</script>

{% endblock %}

{% block content %}


<table id="table_id">
    <thead>
        <tr>
            <th>Job Seeker</th> 
            <th>Mentor</th> 
            <th>Expiration Date</th> 
            <th>First Contact</th> 
            <th>Frequency</th> 
        </tr>
    </thead>
    <tbody>
    {% for m in mentorships %}
        <tr>
            <td> <a href="/dashboard/{{ m.jobseeker.id }}">{{ m.jobseeker }}</a></td>
            <td>{{ m.mentor }}</td>
            <td>{{ m.expirationDate }}</td>
            <td>{{ m.first_contact }}</td>
            <td>{{ m.freq }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<hr/>
</br> <div id="notes">Frequency is times per month. </div> </br> </p>
<a class="button" href="/mentorship/add">Add a mentorship</a>

{% endblock %}

opportunity/templates/err_page.html
{% extends "base.html" %}
{% block content %}

{{ err_msg }}

{% endblock %}

opportunity/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<section class="row">
	<div class="col-md-offset-3 col-md-5">
		<div class="panel panel-default">
			<p class="panel-heading">Welcome! Please login. </p>
			<div class="panel-body">
				
				{% csrf_token %}
				{% if err_pwd %}
					<p class="alert alert-warning">  {{ err_pwd }} </p>
				{% endif %} 
				{% if form.errors %}
					<p class="alert alert-warning">	Please correct the error{{ form.errors|pluralize }} below.</p>
				{% endif %}
				{% crispy form %}
				<!--
				<form class="form-horizontal"action="" method="post">				
			
				{% csrf_token %}
				{% if err_pwd %}
					<p class="alert alert-warning">  {{ err_pwd }} </p>
				{% endif %} 
				{% if form.errors %}
					<p class="bg-warning">	Please correct the error{{ form.errors|pluralize }} below.</p>
				{% endif %}
					<table>
						{{ form.as_table }}
					</table>					
					<input class="btn btn-default"type="submit" value="Submit">
				</form>
				-->
			</div>
			<div class="panel-footer">
				<p class="text-muted">Don't have an account? <a href="/register/">Create one now</a></p>
				<p class="text-muted">Forgot your password? <a href="/resetpassword/">Reset it!</a></p>
			</div>
		</div>
	</div>
</section>

{% endblock %}

opportunity/templates/perm_problem.html
{% extends "base.html" %}
{% block content %}

{{ err_message }} 

{% endblock %}

opportunity/templates/register.html
{% extends "base.html" %}
{% block content %}
Welcome. Please register with this website. 
	<form action="" method="post">
	{% csrf_token %}
	
		{% if form.errors %}
			<p style="color: red;">
				Please correct the error{{ form.errors|pluralize }} below.
			</p>
		{% endif %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="Submit">
	</form>

{% endblock %}

opportunity/templates/tracker_form.html
{% extends "base.html" %}

{% block page_specific_js %} 
        <script src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>
        <script>
            $(function() {
                $("#id_when").datepicker();
                $("#id_startDate").datepicker();
                var d = new Date (); 
                var defaultTime = null;  
                var hours = d.getHours();
                if (hours < 12 ) {
                    defaultTime = hours + ":00 am" ;
                } else {
                    // military time. so subtract 12 
                    hours = hours - 12 
                    defaultTime = hours + ":00 pm" ;
                }
                $("#id_time").val(defaultTime);
                $("#id_time").timepicker({ timeFormat: 'hh:mm tt', seconds: false });
            });
            
        </script>

{% endblock %}

{% block content %}
<!--

We use a variety of forms in this applications. Most can be filled
using this template. If a particular model requires special processing,
copy this template and extend it. 

-->

    <h1>{{ title }}</h1>
    
    {{ desc }} 


    {% if form.errors %}
    <p style="color: red;">
      Please correct the error{{ form.errors|pluralize }} below.
    </p>
    {% endif %}
    
    <form action="" method="post">
      <table>
	{{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
    </form>

{% endblock %}

opportunity/templates/upglo_only.html
{% extends "base.html" %}
{% block content %}

This page is for the Upwardly Global staff. 

{% endblock %}